<?php $this->headTitle("Animal"); ?>
<h1>Animais</h1>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Foto</th>
        <th>Idade</th>
        <th>Sexo</th>
        <th>Cor</th>
        <th>Detalhes</th> 
        <th>Porte</th> 
        <th>ID Raca</th> 
        <th>ID Especie</th> 
        <th>ID Usuario</th> 
    </tr>
    <?php 
    $animals = $this->animals;
//     var_dump($animals);?>
    <?php foreach ($animals as $animal): ?>
        <tr>
            <td><?= $this->escapeHtml($animal['nome']); ?></td>
            <td><img src="data:image/jpeg;base64, <?= base64_encode($animal['foto']);?>"/></td>
            <td><?= $this->escapeHtml($animal['idade']); ?></td>
            <td><?= $this->escapeHtml($animal['sexo']); ?></td>
            <td><?= $this->escapeHtml($animal['cor']); ?></td>
            <td><?= $this->escapeHtml($animal['detalhes']); ?></td>
            <td><?= $this->escapeHtml($animal['porte']); ?></td>
            <td><?= $this->escapeHtml($animal['raca_id']); ?></td>
            <td><?= $this->escapeHtml($animal['especie_id']); ?></td>
            <td><?= $this->escapeHtml($animal['usuario_id']); ?></td>
        </tr>
    <?php endforeach;?>
</table>
