<?php $this->headTitle("Animal"); ?>
<h1>Animais</h1>

<table class="table">
    <tr>
        <th>Nome</th>
        <th>Idade</th>
        <th>Sexo</th>
        <th>Cor</th>
        <th>Detalhes</th> 
    </tr>
    <?php 
    $animals = $this->animals;
//     var_dump($animals);?>
    <?php foreach ($animals as $animal): ?>
        <tr>
            <td><?= $this->escapeHtml($animal['nome']); ?></td>
            <td><img src="data:image/jpeg;base64, <?= base64_encode($animal['foto']);?>"/></td>
            <td><?= $this->escapehtml($animal->sexo);?></td>
            <td><?= $this->escapehtml($animal->cor);?></td>
            <td><?= $this->escapehtmlattr($animal->detalhes);?></td>
        </tr>
    <?php endforeach;?>
</table>
<form>
    <div class="form-group">
        <input type="text" id="lati" name="latitude" class="form-control">
    </div>
    <div class="form-group">
        <input type="text" id="long" name="longitude" class="form-control">
    </div>
</form>
<script>
    window.onload = function (){
      if (window.navigator && window.navigator.geolocation) {
       var geolocation = window.navigator.geolocation;
       geolocation.getCurrentPosition(sucesso, erro);
      } else {
         alert('Geolocalização não suportada em seu navegador.')
      }
      function sucesso(posicao){
        console.log(posicao);
        var latitude = posicao.coords.latitude;
        var longitude = posicao.coords.longitude;
        document.getElementById('lati').value = latitude;
        document.getElementById('long').value = longitude;
//        alert('Sua latitude estimada é: ' + latitude + ' e longitude: ' + longitude )
      }
      function erro(error){
        console.log(error)
      }
    }
</script>