<?php $this->headTitle("Animal"); ?>
<h1>Animais</h1>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Foto</th>
        <th>Sexo</th>
        <th>Detalhes</th>
        <th>ID Raca</th>
        <th>ID Especie</th> 
        <th>ID Usuario</th> 
    </tr>
    <?php
    $animais = $this->$animais;
    Zend\Debug\Debug::dump($animais);
    ?>
    <?php foreach($animais as $animal): ?>
        <tr>
            <td><?= $this->escapeHtml($animal['animal_id']); ?></td>
            <td><?= $this->escapeHtml($animal['nome']); ?></td>
            <td><img src="data:image/jpeg;base64, <?= base64_encode($animal['foto']);?>"/></td>
            <td><?= $this->escapeHtml($animal['sexo']); ?></td>
            <td><?= $this->escapeHtml($animal['detalhes']); ?></td>
            <td><?= $this->escapeHtml($animal['raca_id']); ?></td>
            <td><?= $this->escapeHtml($animal['especie_id']); ?></td>
            <td><?= $this->escapeHtml($animal['usuario_id']); ?></td>
        </tr>
    <?php endforeach;?>
</table>
