 <?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <link href='https://fonts.googleapis.com/css?family=Snippet' rel='stylesheet' type='text/css'>
        <?= $this->headTitle('Localizapet')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))

        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
    </head>
    <?php
        $url = $_SERVER['REQUEST_URI'];
    ?>
    <body <?php if($url == "/") echo 'class="home"';?>>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?= $this->url('home') ?>">
                        <img src="<?= $this->basePath('img/localizapet_logo.png') ?>" height="51" alt="Localizapet <?= \Application\Module::VERSION ?>"/>Localizapet
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li ><a href="<?= $this->url('home') ?>">Mapa</a></li>
                        <li ><a href="<?= $this->url('registro', ['action'=>'busca']) ?>">Busca</a></li>
                        <li ><a href="<?= $this->url('registro', ['action'=>'add']) ?>">Adicionar Registro</a></li>
                        <?php
                            $auth = new Zend\Authentication\AuthenticationService();
                            $url_title = (!$auth->getIdentity()) ? 'Login' :'Sair';
                        ?>
                        <li ><a href="<?= $this->url('usuario') ?>"><?=$url_title?></a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p class="text-center">&copy; 2016 - <?= date('Y') ?> Desenvolvido por
                    <a href="https://www.linkedin.com/in/igorbarato/" target="_blank">Igor Barato</a>.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
