<h1>Novo Usuário</h1>

<?php
    $form = $this->form;
    $messages = $form->getMessages();

    $login = $form->get('login');
    $login->setAttribute('class','form-control');

    $senha = $form->get('senha');
    $senha->setAttribute('class','form-control');

    $telefone = $form->get('telefone');
    $telefone->setAttribute('class','form-control');

    $submit = $form->get('submit');
    $submit->setAttribute('class','btn btn-primary');

    $form->setAttribute('action', $this->url('usuario', ['action'=>'add']));
    $form->prepare();

    echo $this->form()->openTag($form);

?>

<?php if(!empty($messages)): ?>
    <?php foreach($messages as $key => $message_type): ?>
        <div class="alert alert-danger">
            <strong><?=$key?></strong>
            <?php foreach($message_type as $message):?>
                <?=$message?>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<div class="form-group">
    <?=$this->formLabel($login);?>
    <?=$this->formElement($login);?>
</div>

<div class="form-group">
    <?=$this->formLabel($senha);?>
    <?=$this->formElement($senha);?>
</div>

<div class="form-group">
    <?=$this->formLabel($telefone);?>
    <?=$this->formElement($telefone);?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>