<h1>Login</h1>

<?php

$form = $this->form;
$data = $this->data;
$erro = $this->erro;

$login = $form->get('login');
$login->setAttribute('class','form-control');

$senha = $form->get('senha');
$senha->setAttribute('class','form-control');

$submit = $form->get('submit');
$submit->setAttribute('class','btn btn-primary');

$form->setAttribute('action', $this->url('usuario'));
$form->prepare();

echo $this->form()->openTag($form);

?>
<?php if(!empty($erro)):?>
    <div class="alert alert-danger">
        <p><?=$erro;?></p>
    </div>
<?php endif;?>
<div class="form-group">
    <?=$this->formLabel($login);?>
    <?=$this->formElement($login);?>
</div>

<div class="form-group">
    <?=$this->formLabel($senha);?>
    <?=$this->formElement($senha);?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>

