<div class="row">
    <div class="col-xs-12 col-md-4 col-md-offset-4">
        <?php if(!empty($erro)):?>
            <div class="alert alert-danger">
                <p><?=$erro;?></p>
            </div>
        <?php endif;?>
        <div class=" panel panel-success">
            <div class="panel-heading text-center "><h4>Login</h4></div>
            <div class="panel-body">

<?php

$form = $this->form;
$data = $this->data;
$erro = $this->erro;

$login = $form->get('login');
$login->setAttribute('class','form-control');

$senha = $form->get('senha');
$senha->setAttribute('class','form-control');

$submit = $form->get('submit');
$submit->setAttribute('class','btn btn-primary');

$form->setAttribute('action', $this->url('usuario', ['action'=>'login']));
$form->prepare();

echo $this->form()->openTag($form);

?>
<div class="form-group">
    <?=$this->formLabel($login);?>
    <?=$this->formElement($login);?>
</div>

<div class="form-group">
    <?=$this->formLabel($senha);?>
    <?=$this->formElement($senha);?>
</div>
<div class="text-center">
    <?=$this->formSubmit($submit);?> ou <a href="<?=$this->url('usuario', ['action'=>'cadastrar'])?>">Criar nova conta</a>
</div>
<?php

echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
            </div>
        </div>
    </div>
</div>


