<h1>Cadastrar novo Pet</h1>

<?php

$form = $this->form;

$nome = $form->get('nome');
$nome->setAttribute('class','form-control');

$idade = $form->get('idade');
$idade->setAttribute('class','form-control');

$sexo = $form->get('sexo');
$sexo->setAttribute('class','form-control');

$detalhes= $form->get('detalhes');
$detalhes->setAttribute('class','form-control');

$cor= $form->get('cor');
$cor->setAttribute('class','form-control');

$foto= $form->get('foto');
$foto->setAttribute('class','form-control');

$porte= $form->get('porte');
$porte->setAttribute('class','form-control');

$raca= $form->get('raca');
$raca->setAttribute('class','form-control');

$especie= $form->get('especie');
$especie->setAttribute('class','form-control');

$submit = $form->get('submit');
$submit->setAttribute('class','btn btn-primary');

$form->setAttribute('action', $this->url('post', ['action'=>'add']));
$form->prepare();

echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?=$this->formLabel($nome);?>
    <?=$this->formElement($nome);?>
</div>

<div class="form-group">
    <?=$this->formLabel($idade);?>
    <?=$this->formElement($idade);?>
</div>

<div class="form-group">
    <?=$this->formLabel($sexo);?>
    <?=$this->formElement($sexo);?>
</div>

<div class="form-group">
    <?=$this->formLabel($detalhes);?>
    <?=$this->formElement($detalhes);?>
</div>

<div class="form-group">
    <?=$this->formLabel($cor);?>
    <?=$this->formElement($cor);?>
</div>

<div class="form-group">
    <?=$this->formLabel($foto);?>
    <?=$this->formElement($foto);?>
</div>

<div class="form-group">
    <?=$this->formLabel($porte);?>
    <?=$this->formElement($porte);?>
</div>

<div class="form-group">
    <?=$this->formLabel($raca);?>
    <?=$this->formElement($raca);?>
</div>

<div class="form-group">
    <?=$this->formLabel($especie);?>
    <?=$this->formElement($especie);?>
</div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>

