<?php $this->headTitle("Blog"); ?>
<h1>Teste SOAP TCU</h1>


<?php 

$cliente = $this->client;
var_dump($cliente);

echo "<h3>Options:</h3>";
print_r($cliente->getOptions());
// $result = $cliente->soma(11,2);

var_dump($cliente->getLastResponse());



// $client = $this->$client->getOptions();

// var_dump($result);
// var_dump($client);

// $client = $this->client;

// $result = $client->OlaMundo();
// echo $result;


// echo "<h3>Functions:</h3>";
//   print_r($client->getFunctions());

// echo "<h3>Types:</h3>";
//   print_r($client->getTypes());

// echo "<h3>Resultado:</h3>";
// print_r($client->obterSaldoAtualizado([
//     'parcelas' => [
//         'parcela' => [
//             'data' => '1995-01-01',
//             'tipo' => 'D',
//             'valor' => 35000
//         ]
//     ],
//     'aplicaJuros' => 'true',
//     'dataAtualizacao' => '2016-10-31'
// ]));


?>