<?php
    $form = $this->form;
    $messages = $form->getMessages();
?>
<div class="row">
    <div class="col-xs-12">
        <?php if(!empty($messages)): ?>
            <?php foreach($messages as $key => $message_type): ?>
                <div class="alert alert-danger">
                    <strong><?=$key?></strong>
                    <?php foreach($message_type as $message):?>
                        <?=$message?>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class=" panel panel-success">
            <div class="panel-heading "><h4>Novo Registro</h4></div>
            <div class="panel-body">

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.4/js/bootstrap-datetimepicker.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.4/css/bootstrap-datetimepicker.min.css">

<script type="text/javascript">
    $(function () {
        $("[type='datetime']").datetimepicker({
            format: 'DD/MM/YYYY HH:mm'
        });
    });
</script>

<?php


    $data = $form->get('data');
    $data->setAttribute('class','form-control');

    $nome = $form->get('nome');
    $nome->setAttribute('class','form-control');

    $sexo = $form->get('sexo');
    $sexo->setAttribute('class','form-control');

    $detalhes = $form->get('detalhes');
    $detalhes->setAttribute('class','form-control');

    $foto= $form->get('foto');

    $raca= $form->get('raca');
    $raca->setAttribute('class','form-control');

    $endereco = $form->get('endereco');
    $endereco->setAttribute('class','form-control');

    $latitude = $form->get('latitude');
    $latitude->setAttribute('class','form-control');
    $latitude->setAttribute('id','latitude');

    $longitude = $form->get('longitude');
    $longitude->setAttribute('class','form-control');
    $longitude->setAttribute('id','longitude');

    $tipo_registro= $form->get('tipo_registro');
    $tipo_registro->setAttribute('class','form-control');

    $status = $form->get('status');
    $status->setAttribute('class','form-control');

    $submit = $form->get('submit');
    $submit->setAttribute('class','btn btn-primary');

    $form->setAttribute('action', $this->url('registro', ['action'=>'add']));
    $form->prepare();

    echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?=$this->formLabel($tipo_registro);?>
    <?=$this->formElement($tipo_registro);?>
</div>

<div class="form-group">
    <?=$this->formLabel($nome);?>
    <?=$this->formElement($nome);?>
</div>

<div class="form-group">
    <?=$this->formLabel($sexo);?>
    <?=$this->formElement($sexo);?>
</div>

<div class="form-group">
    <?=$this->formLabel($detalhes);?>
    <?=$this->formElement($detalhes);?>
</div>

<div class="form-group">
    <?=$this->formLabel($foto);?>
    <?=$this->formElement($foto);?>
</div>

<div class="form-group">
    <?=$this->formLabel($raca);?>
    <?=$this->formElement($raca);?>
</div>


<div class="form-group">
    <?=$this->formLabel($data);?>
    <?=$this->formElement($data);?>
</div>

<div class="form-group">
    <?=$this->formLabel($endereco);?>
    <?=$this->formElement($endereco);?>
</div>
<!--                <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places?key=AIzaSyBkUY4pGfhYU_aL2UQyy2BrG5A8IBjuEws"></script>-->
<!---->
<!--<input id="autocomplete" placeholder="Enter your address" onFocus="geolocate()" type="text"/>-->
<!--<script>-->
<!--    var autocomplete;-->
<!--    function geolocate() {-->
<!--        autocomplete = new google.map.places.Autocomplete(document.getElementById('autocomplete'));-->
<!--//        google.maps.event.addListener(autocomplete, 'place_changed', geolocate);-->
<!--    }-->
<!--</script>-->

<div class="form-group">
    <?=$this->formLabel($latitude);?>
    <?=$this->formElement($latitude);?>
</div>

<div class="form-group">
    <?=$this->formLabel($longitude);?>
    <?=$this->formElement($longitude);?>
</div>


<div class="form-group">
    <?=$this->formLabel($status);?>
    <?=$this->formElement($status);?>
</div>
<div class="text-center">
    <?=$this->formSubmit($submit);?>
</div>
<?php
echo $this->formHidden($form->get('usuario_id'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>

<script>
    window.onload = function (){
      if (window.navigator && window.navigator.geolocation) {
       var geolocation = window.navigator.geolocation;
       geolocation.getCurrentPosition(sucesso, erro);
      } else {
         alert('Geolocalização não suportada em seu navegador.')
      }
      function sucesso(posicao){
        console.log(posicao);
        var latitude = posicao.coords.latitude;
        var longitude = posicao.coords.longitude;
        document.getElementById('latitude').value = latitude;
        document.getElementById('longitude').value = longitude;
//        alert('Sua latitude estimada é: ' + latitude + ' e longitude: ' + longitude )
      }
      function erro(error){
        console.log(error)
      }
    }
</script>
            </div>
        </div>
    </div>
</div>
