<?php
    $form = $this->form;
    $messages = $form->getMessages();
?>
<div class="row">
    <div class="col-xs-12">
        <?php if(!empty($messages)): ?>
            <?php foreach($messages as $key => $message_type): ?>
                <div class="alert alert-danger">
                    <strong><?=$key?></strong>
                    <?php foreach($message_type as $message):?>
                        <?=$message?>
                    <?php endforeach; ?>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
        <div class=" panel panel-success">
            <div class="panel-heading "><h4>Novo Registro</h4></div>
            <div class="panel-body">
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.4/js/bootstrap-datetimepicker.min.js"></script>
<script type="text/javascript">
    var map;
    function initMap() {
        map = new google.maps.Map(document.getElementById('map-register'), {
            center: {lat: -21.1936966, lng: -47.8377907},
            mapTypeControl: false,
            streetViewControl: false,
            zoom: 17,
            styles: [
                {
                    featureType: "poi",
                    stylers: [
                        {visibility: "off"}
                    ]
                },
                {
                    featureType: "transit",
                    stylers: [
                        {visibility: "off"}
                    ]
                }
            ]
        });

    }
</script>
<script async type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBkUY4pGfhYU_aL2UQyy2BrG5A8IBjuEws&libraries=places&callback=initMap"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/3.1.4/css/bootstrap-datetimepicker.min.css">

<script type="text/javascript">
    $(function () {
        $("[type='datetime']").datetimepicker({
            format: 'DD/MM/YYYY HH:mm'
        });
    });
</script>

<?php


    $data = $form->get('data');
    $data->setAttribute('class','form-control');

    $nome = $form->get('nome');
    $nome->setAttribute('class','form-control');

    $sexo = $form->get('sexo');
    $sexo->setAttribute('class','form-control');

    $detalhes = $form->get('detalhes');
    $detalhes->setAttribute('class','form-control');

    $foto= $form->get('foto');

    $raca= $form->get('raca');
    $raca->setAttribute('class','form-control');

    $endereco = $form->get('endereco');
    $endereco->setAttribute('class','form-control');
    $endereco->setAttribute('id','autocomplete');

    $latitude = $form->get('latitude');
    $latitude->setAttribute('class','form-control');
    $latitude->setAttribute('id','latitude');

    $longitude = $form->get('longitude');
    $longitude->setAttribute('class','form-control');
    $longitude->setAttribute('id','longitude');

    $tipo_registro= $form->get('tipo_registro');
    $tipo_registro->setAttribute('class','form-control');

    $status = $form->get('status');
    $status->setAttribute('class','form-control');

    $submit = $form->get('submit');
    $submit->setAttribute('class','btn btn-primary');

    $form->setAttribute('action', $this->url('registro', ['action'=>'add']));
    $form->prepare();

    echo $this->form()->openTag($form);

?>

<div class="form-group">
    <?=$this->formLabel($tipo_registro);?>
    <?=$this->formElement($tipo_registro);?>
</div>

<div class="form-group">
    <?=$this->formLabel($nome);?>
    <?=$this->formElement($nome);?>
</div>

<div class="form-group">
    <?=$this->formLabel($sexo);?>
    <?=$this->formElement($sexo);?>
</div>

<div class="form-group">
    <?=$this->formLabel($detalhes);?>
    <?=$this->formElement($detalhes);?>
</div>

<div class="form-group">
    <?=$this->formLabel($foto);?>
    <?=$this->formElement($foto);?>
</div>

<div class="form-group">
    <?=$this->formLabel($raca);?>
    <?=$this->formElement($raca);?>
</div>


<div class="form-group">
    <?=$this->formLabel($data);?>
    <?=$this->formElement($data);?>
</div>

<div class="form-group">
    <?=$this->formLabel($endereco);?>
    <?=$this->formElement($endereco);?>
</div>

<div id="map-register" style="width: 100%; height: 300px"></div>

<div style="display: none;">
    <div class="form-group">
        <?=$this->formLabel($latitude);?>
        <?=$this->formElement($latitude);?>
    </div>

    <div class="form-group">
        <?=$this->formLabel($longitude);?>
        <?=$this->formElement($longitude);?>
    </div>
</div>

<div class="form-group">
    <?=$this->formLabel($status);?>
    <?=$this->formElement($status);?>
</div>
<div class="text-center">
    <?=$this->formSubmit($submit);?>
</div>
<?php
echo $this->formHidden($form->get('usuario_id'));
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>

<script>
    var input = document.getElementById('autocomplete');
    var options = {
        componentRestrictions: {
            country: 'br'
        }
    };

    var autocomplete = new google.maps.places.Autocomplete(input, options);
    var marker = "";

    google.maps.event.addListener(autocomplete, 'place_changed', function () {

        var place = autocomplete.getPlace();
        var lat = place.geometry.location.lat();
        var long = place.geometry.location.lng();
        document.getElementById('latitude').value = lat;
        document.getElementById('longitude').value = long;
        marker.setMap(null);
        var newLatLng = new google.maps.LatLng(lat, long);

        marker = new google.maps.Marker({
            position: newLatLng,
            map: map,
            draggable: true
        });
        map.setCenter(newLatLng);
        marker.setPosition(newLatLng);

    });

    window.onload = function (){
      if (window.navigator && window.navigator.geolocation) {
       var geolocation = window.navigator.geolocation;
       geolocation.getCurrentPosition(sucesso, erro);
      } else {
         alert('Geolocalização não suportada em seu navegador.')
      }
      function sucesso(posicao){
        //console.log(posicao);
        var latitude = posicao.coords.latitude;
        var longitude = posicao.coords.longitude;
        document.getElementById('latitude').value = latitude;
        document.getElementById('longitude').value = longitude;
          var newLatLng = new google.maps.LatLng(latitude, longitude);
          marker = new google.maps.Marker({
              position: newLatLng,
              map: map,
              draggable: true
          });
          map.setCenter(newLatLng);
          marker.setPosition(newLatLng);
//        alert('Sua latitude estimada é: ' + latitude + ' e longitude: ' + longitude )
      }
      function erro(error){
        console.log(error)
      }
    };

</script>
<!--<script async defer type="text/javascript" src="https://maps.googleapis.com/maps/api/js?callback=initMap"></script>-->

            </div>
        </div>
    </div>
</div>
