<?php $this->headTitle("Registros"); ?>
<h1>Registros</h1>

<?php
$form = $this->form;
$messages = $form->getMessages();

//$data = $form->get('data');
//$data->setAttribute('class','form-control');

$sexo = $form->get('sexo');
$sexo->setAttribute('class','form-control');
$sexo->setValue(-1);

$raca= $form->get('raca');
$raca->setAttribute('class','form-control');
$raca->setValue(-1);

//$animal_id = $form->get('animal_id');
//$animal_id->setAttribute('class','form-control');

$submit = $form->get('submit');
$submit->setAttribute('class','btn btn-primary');

$form->setAttribute('action', $this->url('registro', ['action'=>'busca']));
$form->prepare();

echo $this->form()->openTag($form);

?>

<?php if(!empty($messages)): ?>
    <?php foreach($messages as $key => $message_type): ?>
        <div class="alert alert-danger">
            <strong><?=$key?></strong>
            <?php foreach($message_type as $message):?>
                <?=$message?>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<div class="form-group">
    <?=$this->formLabel($sexo);?>
    <?=$this->formElement($sexo);?>
</div>

<div class="form-group">
    <?=$this->formLabel($raca);?>
    <?=$this->formElement($raca);?>
</div>



<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
<br>
<div class="table-responsive">
    <table class="table table-hover">
        <tr>
            <th>Foto</th>
            <th>Informações do Animal</th>
            <th>Tipo de registro</th>
            <th>Data</th>
            <th>Endereço</th>
            <th>Status</th>
            <th>Usuário</th>
        </tr>
        <?php
        $registros = $this->registros;
        if(isset($registros)):
    //    \Zend\Debug\Debug::dump($registros);?>
        <?php foreach ($registros as $registro): ?>
            <tr class="<?=($registro->tipo_registro == 0) ? 'danger' : 'success'?>">
                <td><img width="100px" height="auto" src="data:image/jpeg;base64,<?=$registro->{'foto'}?>"/></td>
                <td>
                <?php if($registro->nome != "") echo "<span style='font-size: 16px'><strong>" . $registro->nome . "</strong></span><br>";  ?>
                <i class="fa fa-venus-mars" aria-hidden="true"></i> <?= ($registro->sexo == 0 ) ? "Fêmea" : "Macho" ?>
                <br><i class="fa fa-paw" aria-hidden="true"></i> <?= ($registro->raca->especie == 0) ? "Cachorro" : "Gato" ?>
                <br><i class="fa fa-paw" aria-hidden="true"></i> <?= $registro->raca->raca ?>
                <br><i class="fa fa-info-circle" aria-hidden="true"></i> <?= $registro->detalhes ?>
                </td>
                <td><?= ($registro->tipo_registro == 0) ? "Perdido" : "Encontrado" ?></td>
                <td><?= $registro->data ?></td>
                <td><?= $registro->endereco ?><br><a class="btn btn-primary" onclick="myNavFunc()"><i class="fa fa-map-marker" aria-hidden="true"></i> ver no Maps</a></td>
                <td><?= $registro->status ?></td>
                <td class="text-center"><?= $registro->usuario->login ?><br><a class="btn btn-primary" href="tel:<?= $registro->usuario->telefone ?>"><?= $registro->usuario->telefone ?><br><i class="fa fa-phone" aria-hidden="true"></i> ligar</a></td>

            </tr>
                <script>
                    function myNavFunc(){
                        if( (navigator.platform.indexOf("iPhone") != -1)
                            || (navigator.platform.indexOf("iPod") != -1)
                            || (navigator.platform.indexOf("iPad") != -1))
                            window.open("maps://maps.google.com/maps?daddr=<?= $registro->latitude ?>,<?= $registro->longitude ?>&amp;ll=");
                        else
                            window.open("http://maps.google.com/maps?daddr=<?= $registro->latitude ?>,<?= $registro->longitude ?>&amp;ll=");
                    }
                </script>
        <?php endforeach;?>
        <?php endif;?>
    </table>
</div>
<?php if(count($registros)==0) echo '<div class="text-center alert alert-warning" role="alert">Nenhum resultado encontrado</div>'; ?>




