<?php $this->headTitle("Registros"); ?>
<h1>Registros</h1>

<?php
$form = $this->form;
$messages = $form->getMessages();

//$data = $form->get('data');
//$data->setAttribute('class','form-control');

$sexo = $form->get('sexo');
$sexo->setAttribute('class','form-control');
$sexo->setValue(-1);

$raca= $form->get('raca');
$raca->setAttribute('class','form-control');
$raca->setValue(-1);

//$animal_id = $form->get('animal_id');
//$animal_id->setAttribute('class','form-control');

$submit = $form->get('submit');
$submit->setAttribute('class','btn btn-primary');

$form->setAttribute('action', $this->url('registro', ['action'=>'busca']));
$form->prepare();

echo $this->form()->openTag($form);

?>

<?php if(!empty($messages)): ?>
    <?php foreach($messages as $key => $message_type): ?>
        <div class="alert alert-danger">
            <strong><?=$key?></strong>
            <?php foreach($message_type as $message):?>
                <?=$message?>
            <?php endforeach; ?>
        </div>
    <?php endforeach; ?>
<?php endif; ?>

<div class="form-group">
    <?=$this->formLabel($sexo);?>
    <?=$this->formElement($sexo);?>
</div>

<div class="form-group">
    <?=$this->formLabel($raca);?>
    <?=$this->formElement($raca);?>
</div>



<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>

<table class="table table-hover">
    <tr>
        <th>Foto</th>
        <th>Tipo de registro</th>
        <th>Nome</th>
        <th>Data</th>
        <th>Sexo</th>
        <th>Espécie</th>
        <th>Raça</th>
        <th>Detalhes</th>
        <th>Endereço</th>
        <th>Latitude</th>
        <th>Longitude</th>
        <th>Status</th>
        <th>Usuário</th>
    </tr>
    <?php
    $registros = $this->registros;
//    \Zend\Debug\Debug::dump($registros);?>
    <?php foreach ($registros as $registro): ?>
        <tr>
            <td><img width="100px" height="auto" src="data:image/jpeg;base64,<?=$registro->{'foto'}?>"/></td>
            <td><?= ($registro->tipo_registro == 0) ? "Perdido" : "Encontrado" ?></td>
            <td><?= $registro->nome ?></td>
            <td><?= $registro->data ?></td>
            <td><?= ($registro->sexo == 0 ) ? "Fêmea" : "Macho" ?></td>
            <td><?= ($registro->raca->especie == 0) ? "Cachorro" : "Gato" ?></td>
            <td><?= $registro->raca->raca ?></td>
            <td><?= $registro->detalhes ?></td>
            <td><?= $registro->endereco ?></td>
            <td><?= $registro->latitude ?></td>
            <td><?= $registro->longitude ?></td>
            <td><?= $registro->status ?></td>
            <td><?= $registro->usuario->login ?></td>
        </tr>
    <?php endforeach;?>
</table>

<?php if(count($registros)==0) echo '<div class="text-center alert alert-warning" role="alert">Nenhum resultado encontrado</div>'; ?>
