<?php $this->headTitle("Home"); ?>
<div id="map"></div>
<script>
    var map;
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: -21.1936966, lng: -47.8377907},
            mapTypeControl: false,
            streetViewControl: false,
            zoom: 17,
            styles: [
                {
                    featureType: "poi",
                    stylers: [
                        { visibility: "off" }
                    ]
                },
                {
                    featureType: "transit",
                    stylers: [
                        { visibility: "off" }
                    ]
                }
            ]
        });


        var icons = {
            C:{
                perdido: {
                    icon: '/img/red_MarkerC.png'
                },
                encontrado: {
                    icon: '/img/green_MarkerC.png'
                }
            },
            G: {
                perdido: {
                    icon: '/img/red_MarkerG.png'
                },
                encontrado: {
                    icon: '/img/green_MarkerG.png'
                }
            }
        };

        var locations = [
            <?php foreach ($registros as $registro): ?>
            {
                id: <?= $registro->id ?>,
                nome: '<?= $registro->nome ?>',
                data: '<?php print date("d/m/Y", strtotime($registro->data)); ?>',
                latitude: <?= $registro->latitude ?>,
                longitude: <?= $registro->longitude ?>,
                label: <?php ($registro->raca->especie == 0) ? print "\"C\"" : print "\"G\"";?>,
                type:  <?php ($registro->tipo_registro == 0) ? print "\"perdido\"" : print "\"encontrado\"";?>,
                foto: "<?=$registro->foto?>",
                sexo: "<?php ($registro->sexo == 0) ? print "Fêmea" : print "Macho";?>",
                raca: "<?= $registro->raca->raca ?>"},
            <?php endforeach;?>
        ];



        var infowindow = new google.maps.InfoWindow()
//        infowindow.setContent(content);

        for (i = 0; i < locations.length; i++) {

                marker = new google.maps.Marker({
                position: new google.maps.LatLng(locations[i]['latitude'], locations[i]['longitude']),
                title: locations[i]['nome'],
                icon: icons[locations[i].label][locations[i].type].icon,
                    desc:   '<div class="widget-header ' + locations[i].type + '"></div>' +
                            '<div class="box-pet">' +
                                '<img class="img-circle img-border-light" src="data:image/jpeg;base64,'+locations[i].foto+'"/>' +
                                '<h4 class="text-center">' + locations[i].nome + '</h4>' +
                                '<div><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> '+ locations[i].data + '</div>' +
                                '<div><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> Sexo: '+ locations[i].sexo + '</div>' +
                                '<div><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Raça: '+ locations[i].raca + '</div>' +
                                '<button type="button" class="btn btn-primary btn-block">' +
                                   '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> detalhes' +
                                '</button>' +
                            '</div>',
                    map: map
            });


            google.maps.event.addListener(marker,'click', (function(marker,infowindow){
                return function() {
                    infowindow.setContent(marker.desc);
                    infowindow.open(map,marker);
                    var iwOuter = $('.gm-style-iw');

                    /* Uma vez que o div pretendido está numa posição anterior ao div .gm-style-iw.
                     * Recorremos ao jQuery e criamos uma variável iwBackground,
                     * e aproveitamos a referência já existente do .gm-style-iw para obter o div anterior com .prev().
                     */
                    var iwBackground = iwOuter.prev();

                    // Remover o div da sombra do fundo
                    iwBackground.children(':nth-child(2)').css({'display' : 'none'});

                    // Remover o div de fundo branco
                    iwBackground.children(':nth-child(4)').css({'display' : 'none'});

                    // Desloca a sombra da seta a 76px da margem esquerda
//                    iwBackground.children(':nth-child(1)').attr('style', function(i,s){ return s + 'left: 76px !important;'});

                    // Desloca a seta a 76px da margem esquerda
//                    iwBackground.children(':nth-child(3)').attr('style', function(i,s){ return s + 'left: 76px !important;'});
                };
            })(marker,infowindow));

        }




    }
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBkUY4pGfhYU_aL2UQyy2BrG5A8IBjuEws&callback=initMap">
</script>