<?php $this->headTitle("Home"); ?>
<div id="map"></div>
<script>
    var map;
    var latitude, longitude;

    if (window.navigator && window.navigator.geolocation) {
        var geolocation = window.navigator.geolocation;
        geolocation.getCurrentPosition(sucesso, erro);
    } else {
        alert('Geolocalização não suportada em seu navegador.')
    }
    function sucesso(posicao){
        latitude = posicao.coords.latitude;
        longitude = posicao.coords.longitude;
        console.log(posicao.coords.latitude)
        console.log(posicao.coords.longitude);
    }
    function erro(error){
        console.log(error)
    }
    function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: latitude, lng: longitude},
            mapTypeControl: false,
            streetViewControl: false,
            zoom: 17,
            styles: [
                {
                    featureType: "poi",
                    stylers: [
                        { visibility: "off" }
                    ]
                },
                {
                    featureType: "transit",
                    stylers: [
                        { visibility: "off" }
                    ]
                }
            ]
        });
//        directionsDisplay = new google.maps.DirectionsRenderer();
//        map.setMyLocationEnabled(true);


        var icons = {
            C:{
                perdido_p: {
                    icon: '/img/red_MarkerC.png'
                },
                encontrado_p: {
                    icon: '/img/green_MarkerC.png'
                },
                perdido_c: {
                    icon: '/img/blue_MarkerC.png'
                },
                encontrado_c: {
                    icon: '/img/blue_MarkerC.png'
                }
            },
            G: {
                perdido_p: {
                    icon: '/img/red_MarkerG.png'
                },
                encontrado_p: {
                    icon: '/img/green_MarkerG.png'
                },
                perdido_c: {
                    icon: '/img/blue_MarkerG.png'
                },
                encontrado_c: {
                    icon: '/img/blue_MarkerG.png'
                }
            }
        };

        var locations = [
            <?php foreach ($registros as $registro): ?>
            {
                id: <?= $registro->id ?>,
                nome: '<?= $registro->nome ?>',
                data: '<?php print date("d/m/Y", strtotime($registro->data)); ?>',
                latitude: <?= $registro->latitude ?>,
                longitude: <?= $registro->longitude ?>,
                label: <?php ($registro->raca->especie == 0) ? print "\"C\"" : print "\"G\"";?>,
                type:  <?php
                if($registro->status == 1) ($registro->tipo_registro == 0) ? print "\"perdido_c\"" : print "\"encontrado_c\"";
                else ($registro->tipo_registro == 0) ? print "\"perdido_p\"" : print "\"encontrado_p\"";
                ?>,
                foto: "<?=$registro->foto?>",
                sexo: "<?php ($registro->sexo == 0) ? print "Fêmea" : print "Macho";?>",
                raca: "<?= $registro->raca->raca ?>"},
            <?php endforeach;?>
        ];



        var infowindow = new google.maps.InfoWindow()
//        infowindow.setContent(content);

        for (i = 0; i < locations.length; i++) {

                marker = new google.maps.Marker({
                position: new google.maps.LatLng(locations[i]['latitude'], locations[i]['longitude']),
                title: locations[i]['nome'],
                icon: icons[locations[i].label][locations[i].type].icon,
                    desc:   '<div class="widget-header ' + locations[i].type + '"></div>' +
                            '<div class="box-pet">' +
                                '<img class="img-circle img-border-light" src="data:image/jpeg;base64,'+locations[i].foto+'"/>' +
                                '<h4 class="text-center">' + locations[i].nome + '</h4>' +
                                '<div><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> '+ locations[i].data + '</div>' +
                                '<div><span class="glyphicon glyphicon-heart" aria-hidden="true"></span> Sexo: '+ locations[i].sexo + '</div>' +
                                '<div><span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> Raça: '+ locations[i].raca + '</div>' +
                                '<a href="/registro/ver/' + locations[i].id + '" class="btn btn-primary btn-block">' +
                                   '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> detalhes' +
                                '</a>' +
                            '</div>',
                    map: map
            });


            google.maps.event.addListener(marker,'click', (function(marker,infowindow){
                return function() {
                    infowindow.setContent(marker.desc);
                    infowindow.open(map,marker);
                    var iwOuter = $('.gm-style-iw');

                    /* Uma vez que o div pretendido está numa posição anterior ao div .gm-style-iw.
                     * Recorremos ao jQuery e criamos uma variável iwBackground,
                     * e aproveitamos a referência já existente do .gm-style-iw para obter o div anterior com .prev().
                     */
                    var iwBackground = iwOuter.prev();

                    // Remover o div da sombra do fundo
                    iwBackground.children(':nth-child(2)').css({'display' : 'none'});

                    // Remover o div de fundo branco
                    iwBackground.children(':nth-child(4)').css({'display' : 'none'});

                    // Desloca a sombra da seta a 76px da margem esquerda
//                    iwBackground.children(':nth-child(1)').attr('style', function(i,s){ return s + 'left: 76px !important;'});

                    // Desloca a seta a 76px da margem esquerda
//                    iwBackground.children(':nth-child(3)').attr('style', function(i,s){ return s + 'left: 76px !important;'});
                };
            })(marker,infowindow));

        }




    }
//    window.onload = function (){
//        if (window.navigator && window.navigator.geolocation) {
//            var geolocation = window.navigator.geolocation;
//            geolocation.getCurrentPosition(sucesso, erro);
//        } else {
//            alert('Geolocalização não suportada em seu navegador.')
//        }
//        function sucesso(posicao){
//            //console.log(posicao);
//            var latitude = posicao.coords.latitude;
//            var longitude = posicao.coords.longitude;
//            var newLatLng = new google.maps.LatLng(latitude, longitude);
//            marker = new google.maps.Marker({
//                position: newLatLng,
//                map: map,
//                draggable: true
//            });
//            map.setCenter(newLatLng);
//        }
//        function erro(error){
//            console.log(error)
//        }
//    };
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBkUY4pGfhYU_aL2UQyy2BrG5A8IBjuEws&callback=initMap">
</script>