<?php $this->headTitle("Detalhes"); ?>

<?php
    $registro = $this->registro[0];
?>

<div class="row">
    <div class="col-xs-12 ">
        <div class=" panel panel-<?= ($registro->tipo_registro == 0) ? "danger" : "success" ?>">
            <div class="panel-heading text-center "><h4>Informações do animal</h4></div>
            <div class="panel-body">
                <div class="col-lg-5 col-xs-12">
                    <img width="100%" height="auto" src="data:image/jpeg;base64,<?=$registro->{'foto'}?>"/>
                </div>
                <div class="col-lg-7 col-xs-12">
                    <?php if($registro->nome != "") echo "<p style='font-size: 26px'><strong>" . $registro->nome . "</strong></p><br>";  ?>
                    <p><i class="fa fa-venus-mars" aria-hidden="true"></i> <?= ($registro->sexo == 0 ) ? "Fêmea" : "Macho" ?></p>
                    <p><i class="fa fa-paw" aria-hidden="true"></i> <?= ($registro->raca->especie == 0) ? "Cachorro" : "Gato" ?></p>
                    <p><i class="fa fa-paw" aria-hidden="true"></i> <?= $registro->raca->raca ?></p>
                    <p><i class="fa fa-info-circle" aria-hidden="true"></i> <?= $registro->detalhes ?></p>
                    <p><i class="fa fa-tag" aria-hidden="true"></i> <?= ($registro->tipo_registro == 0) ? "Perdido" : "Encontrado" ?></p>
                    <p><i class="fa fa-clock-o" aria-hidden="true"></i> <?= $registro->data ?></p>
                    <p><i class="fa fa-map-marker" aria-hidden="true"></i> <?= $registro->endereco ?><br>
                        <span class="text-center">
                            <a class="btn btn-primary" onclick="myNavFunc()">ver no Maps</a>
                        </span>
                    </p>
                    <p><i class="fa fa-phone" aria-hidden="true"></i> <?= $registro->usuario->login ?><br>
                        <span class="text-center">
                            <a class="btn btn-primary" href="tel:<?= $registro->usuario->telefone ?>"><?= $registro->usuario->telefone ?>
                                <br> ligar</a>
                        </span>
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function myNavFunc(){
        if( (navigator.platform.indexOf("iPhone") != -1)
            || (navigator.platform.indexOf("iPod") != -1)
            || (navigator.platform.indexOf("iPad") != -1))
            window.open("maps://maps.google.com/maps?daddr=<?= $registro->latitude ?>,<?= $registro->longitude ?>&amp;ll=");
        else
            window.open("http://maps.google.com/maps?daddr=<?= $registro->latitude ?>,<?= $registro->longitude ?>&amp;ll=");
    }
</script>




